import * as fs from 'fs';
import * as path from 'path';
import { DeployConfig } from './deploy.config';
import { AppLoggerFactory } from '@node-yalc/logger/logger.factory.js';
import { InternalServerError } from '@node-yalc/errors/error.class.js';

const logger = AppLoggerFactory('DeployFactory');

export class DeployFactory {
  /**
   * Generates the required infrastructure-as-code files based on the chosen strategy.
   * This removes the need for manual configuration and ensures enterprise-standard deployments.
   */
  public static generateDeployment(config: DeployConfig, outputDir: string = './deploy'): void {
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    switch (config.strategy) {
      case 'docker':
        this.generateDocker(config, outputDir);
        break;
      case 'kubernetes':
        this.generateKubernetes(config, outputDir);
        break;
      case 'argocd':
        this.generateArgoCD(config, outputDir);
        break;
      case 'terraform':
        this.generateTerraform(config, outputDir);
        break;
      default:
        throw new InternalServerError(`Unsupported deploy strategy: ${config.strategy}`);
    }

    logger.log(`Successfully generated ${config.strategy} files in ${outputDir}`);
  }

  private static generateDocker(config: DeployConfig, outputDir: string): void {
    const dockerfile = `
# AUTO-GENERATED BY FERROX DEPLOY FACTORY
FROM ${config.baseImage || 'node:20-alpine'} AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM ${config.baseImage || 'node:20-alpine'}
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production

EXPOSE ${config.port}
ENV NODE_ENV=${config.environment}
CMD ["node", "dist/index.js"]
    `.trim();

    fs.writeFileSync(path.join(outputDir, 'Dockerfile'), dockerfile);
  }

  private static generateKubernetes(config: DeployConfig, outputDir: string): void {
    const deployment = `
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${config.appName}
  namespace: ${config.namespace || 'default'}
spec:
  replicas: ${config.replicas || 1}
  selector:
    matchLabels:
      app: ${config.appName}
  template:
    metadata:
      labels:
        app: ${config.appName}
    spec:
      containers:
      - name: ${config.appName}
        image: ${config.dockerRegistry ? config.dockerRegistry + '/' : ''}${config.appName}:${config.version}
        ports:
        - containerPort: ${config.port}
        resources:
          limits:
            cpu: "${config.cpuLimit || '500m'}"
            memory: "${config.memoryLimit || '512Mi'}"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ${config.appName}-svc
  namespace: ${config.namespace || 'default'}
spec:
  selector:
    app: ${config.appName}
  ports:
    - protocol: TCP
      port: 80
      targetPort: ${config.port}
  type: ClusterIP
    `.trim();

    fs.writeFileSync(path.join(outputDir, 'k8s-deployment.yaml'), deployment);
  }

  private static generateArgoCD(config: DeployConfig, outputDir: string): void {
    const application = `
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${config.appName}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '${config.repoUrl || 'https://github.com/your-org/your-repo.git'}'
    targetRevision: ${config.targetRevision || 'HEAD'}
    path: k8s/${config.appName}
  destination:
    server: '${config.destinationServer || 'https://kubernetes.default.svc'}'
    namespace: ${config.namespace || 'default'}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    `.trim();

    fs.writeFileSync(path.join(outputDir, 'argocd-app.yaml'), application);
  }

  private static generateTerraform(config: DeployConfig, outputDir: string): void {
    const tf = `
# AUTO-GENERATED BY FERROX DEPLOY FACTORY
provider "${config.cloudProvider || 'aws'}" {
  region = "${config.region || 'us-east-1'}"
}

resource "${config.cloudProvider === 'aws' ? 'aws_ecs_cluster' : 'google_container_cluster'}" "${config.appName}_cluster" {
  name = "${config.appName}-cluster-${config.environment}"
}
    `.trim();

    fs.writeFileSync(path.join(outputDir, 'main.tf'), tf);
  }
}
