import 'reflect-metadata';

/**
 * A generic type representing a class constructor that can be instantiated.
 * Used internally by the Dependency Injection container to resolve class metadata.
 * 
 * @template T The type of the class being instantiated
 */
type Constructor<T = any> = new (...args: any[]) => T;

/**
 * Enterprise-grade Dependency Injection (DI) Container for Ferrox-Node.
 * 
 * Implements an Inversion of Control (IoC) pattern using Reflection API (`reflect-metadata`).
 * It automatically maps class constructors and their parameter types, resolving the full
 * dependency tree at runtime. Supports singleton pattern and circular dependency detection.
 * 
 * @example
 * ```typescript
 * const container = FerroxDIContainer.getInstance();
 * const service = container.resolve(MyService);
 * ```
 */
export class FerroxDIContainer {
  /** The singleton instance of the DI Container. */
  private static instance = new FerroxDIContainer();
  /** Registry holding mapped singleton instances mapped to their tokens/constructors. */
  private providers = new Map<any, any>();
  /** A tracking set used to detect and prevent circular dependencies during resolution. */
  private resolving = new Set<any>();

  /** Private constructor enforcing the Singleton design pattern. */
  private constructor() {}

  /**
   * Retrieves the globally accessible singleton instance of the DI Container.
   * @returns {FerroxDIContainer} The current container instance.
   */
  public static getInstance(): FerroxDIContainer {
    return FerroxDIContainer.instance;
  }

  /**
   * Manually registers a specific instance or provider against a token.
   * Useful for registering mock instances during testing, or third-party non-class objects.
   * 
   * @param token The token or class constructor serving as the lookup key.
   * @param provider The actual instance or value to inject when the token is requested.
   */
  public register<T>(token: any, provider: T): void {
    this.providers.set(token, provider);
  }

  /**
   * Resolves an instance of the requested class.
   * 
   * If the instance already exists in the container (singleton), it is returned.
   * Otherwise, it inspects the constructor metadata, recursively resolves all dependencies,
   * instantiates the class, caches it as a singleton, and returns it.
   * 
   * @template T
   * @param {Constructor<T>} target The class constructor to resolve and instantiate.
   * @returns {T} The fully instantiated class with all dependencies injected.
   * @throws {Error} If a circular dependency is detected in the dependency graph.
   */
  public resolve<T>(target: Constructor<T>): T {
    if (this.providers.has(target)) {
      return this.providers.get(target);
    }

    if (this.resolving.has(target)) {
      throw new Error(`Circular dependency detected while resolving ${target.name}`);
    }

    this.resolving.add(target);

    // Get injection tokens (constructor parameters) generated by TypeScript's emitDecoratorMetadata
    const tokens = Reflect.getMetadata('design:paramtypes', target) || [];
    
    // Resolve all dependencies recursively
    const injections = tokens.map((token: any) => this.resolve(token));

    // Instantiate with dependencies injected
    const instance = new target(...injections);
    
    // Register as a singleton for future resolutions
    this.providers.set(target, instance);
    this.resolving.delete(target);

    return instance;
  }
}

